// =====================================================
// LIGHTNING LEDGERZ - DATA EXPORT SYSTEM
// Export data to CSV, Excel, PDF, and more
// =====================================================

class DataExport {
    constructor() {
        this.exportHistory = [];
    }

    // =====================================================
    // CSV EXPORT
    // =====================================================

    toCSV(data, options = {}) {
        const { headers = true, delimiter = ',', filename = 'export.csv' } = options;

        if (!Array.isArray(data) || data.length === 0) {
            throw new Error('Data must be a non-empty array');
        }

        let csv = '';

        // Headers
        if (headers) {
            const headerRow = Object.keys(data[0]);
            csv += headerRow.join(delimiter) + '\n';
        }

        // Data rows
        data.forEach(row => {
            const values = Object.values(row).map(value => {
                // Escape quotes and wrap in quotes if contains delimiter or newline
                const stringValue = String(value);
                if (stringValue.includes(delimiter) || stringValue.includes('\n') || stringValue.includes('"')) {
                    return '"' + stringValue.replace(/"/g, '""') + '"';
                }
                return stringValue;
            });
            csv += values.join(delimiter) + '\n';
        });

        return { csv, filename };
    }

    downloadCSV(data, options = {}) {
        const { csv, filename } = this.toCSV(data, options);
        this.downloadFile(csv, filename, 'text/csv');
        this.trackExport('CSV', filename);
    }

    // =====================================================
    // EXCEL EXPORT (uses SheetJS if available)
    // =====================================================

    toExcel(data, options = {}) {
        const { filename = 'export.xlsx', sheetName = 'Sheet1' } = options;

        if (typeof XLSX === 'undefined') {
            console.warn('SheetJS (XLSX) not loaded, falling back to CSV');
            return this.downloadCSV(data, { ...options, filename: filename.replace('.xlsx', '.csv') });
        }

        const worksheet = XLSX.utils.json_to_sheet(data);
        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);

        return { workbook, filename };
    }

    downloadExcel(data, options = {}) {
        if (typeof XLSX === 'undefined') {
            this.downloadCSV(data, { ...options, filename: (options.filename || 'export').replace('.xlsx', '.csv') });
            return;
        }

        const { workbook, filename } = this.toExcel(data, options);
        XLSX.writeFile(workbook, filename);
        this.trackExport('Excel', filename);
    }

    // =====================================================
    // PDF EXPORT (using browser print or jsPDF)
    // =====================================================

    toPDF(content, options = {}) {
        const { title = 'Export', filename = 'export.pdf', orientation = 'portrait' } = options;

        // Create printable content
        const printWindow = window.open('', '_blank');
        printWindow.document.write(`
            <!DOCTYPE html>
            <html>
            <head>
                <title>${title}</title>
                <style>
                    body {
                        font-family: 'Segoe UI', Arial, sans-serif;
                        padding: 40px;
                        color: #333;
                    }
                    h1 { color: #ff3333; border-bottom: 2px solid #f39c12; padding-bottom: 10px; }
                    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
                    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
                    th { background: #f5f5f5; font-weight: 600; }
                    .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
                    .logo { font-size: 24px; font-weight: bold; color: #ff3333; }
                    .date { color: #888; }
                    .footer { margin-top: 40px; text-align: center; color: #888; font-size: 12px; }
                    @media print {
                        body { padding: 20px; }
                        .no-print { display: none; }
                    }
                </style>
            </head>
            <body>
                <div class="header">
                    <div class="logo">⚡ Lightning Ledgerz</div>
                    <div class="date">${new Date().toLocaleDateString()}</div>
                </div>
                <h1>${title}</h1>
                ${content}
                <div class="footer">
                    Generated by Lightning Ledgerz | ${new Date().toLocaleString()}
                </div>
                <script>
                    window.onload = function() { window.print(); }
                </script>
            </body>
            </html>
        `);
        printWindow.document.close();

        this.trackExport('PDF', filename);
    }

    // =====================================================
    // JSON EXPORT
    // =====================================================

    toJSON(data, options = {}) {
        const { filename = 'export.json', pretty = true } = options;
        const json = pretty ? JSON.stringify(data, null, 2) : JSON.stringify(data);
        return { json, filename };
    }

    downloadJSON(data, options = {}) {
        const { json, filename } = this.toJSON(data, options);
        this.downloadFile(json, filename, 'application/json');
        this.trackExport('JSON', filename);
    }

    // =====================================================
    // TABLE TO EXPORTABLE DATA
    // =====================================================

    tableToData(tableSelector) {
        const table = document.querySelector(tableSelector);
        if (!table) return [];

        const headers = [];
        const rows = [];

        // Get headers
        const headerCells = table.querySelectorAll('thead th');
        headerCells.forEach(th => headers.push(th.textContent.trim()));

        // Get rows
        const bodyRows = table.querySelectorAll('tbody tr');
        bodyRows.forEach(tr => {
            const row = {};
            const cells = tr.querySelectorAll('td');
            cells.forEach((td, i) => {
                row[headers[i] || `Column${i}`] = td.textContent.trim();
            });
            rows.push(row);
        });

        return rows;
    }

    // =====================================================
    // FINANCIAL REPORT EXPORT
    // =====================================================

    exportFinancialReport(reportType = 'summary') {
        const data = this.getFinancialData(reportType);

        return {
            toCSV: () => this.downloadCSV(data, { filename: `financial_${reportType}_${this.dateStamp()}.csv` }),
            toExcel: () => this.downloadExcel(data, { filename: `financial_${reportType}_${this.dateStamp()}.xlsx` }),
            toPDF: () => this.toPDF(this.formatReportAsHTML(data, reportType), { title: `Financial ${reportType}`, filename: `financial_${reportType}_${this.dateStamp()}.pdf` }),
            toJSON: () => this.downloadJSON(data, { filename: `financial_${reportType}_${this.dateStamp()}.json` })
        };
    }

    getFinancialData(reportType) {
        // Use financial analysis data if available
        if (window.financialAnalysisPro) {
            const ratios = window.financialAnalysisPro.calculateRatios();

            switch (reportType) {
                case 'summary':
                    return [
                        { Metric: 'Revenue', Value: '$' + ratios.absolute.revenue.toLocaleString() },
                        { Metric: 'Gross Profit', Value: '$' + ratios.absolute.grossProfit.toLocaleString() },
                        { Metric: 'Operating Income', Value: '$' + ratios.absolute.operatingIncome.toLocaleString() },
                        { Metric: 'Net Income', Value: '$' + ratios.absolute.netIncome.toLocaleString() },
                        { Metric: 'Gross Margin', Value: (ratios.profitability.grossMargin * 100).toFixed(1) + '%' },
                        { Metric: 'Net Margin', Value: (ratios.profitability.netMargin * 100).toFixed(1) + '%' },
                        { Metric: 'ROIC', Value: (ratios.profitability.roic * 100).toFixed(1) + '%' },
                        { Metric: 'Current Ratio', Value: ratios.liquidity.currentRatio.toFixed(2) },
                        { Metric: 'Debt/Equity', Value: ratios.leverage.debtToEquity.toFixed(2) }
                    ];

                case 'ratios':
                    return [
                        { Category: 'Profitability', Metric: 'Gross Margin', Value: (ratios.profitability.grossMargin * 100).toFixed(1) + '%' },
                        { Category: 'Profitability', Metric: 'Operating Margin', Value: (ratios.profitability.operatingMargin * 100).toFixed(1) + '%' },
                        { Category: 'Profitability', Metric: 'Net Margin', Value: (ratios.profitability.netMargin * 100).toFixed(1) + '%' },
                        { Category: 'Profitability', Metric: 'ROE', Value: (ratios.profitability.roe * 100).toFixed(1) + '%' },
                        { Category: 'Profitability', Metric: 'ROA', Value: (ratios.profitability.roa * 100).toFixed(1) + '%' },
                        { Category: 'Profitability', Metric: 'ROIC', Value: (ratios.profitability.roic * 100).toFixed(1) + '%' },
                        { Category: 'Liquidity', Metric: 'Current Ratio', Value: ratios.liquidity.currentRatio.toFixed(2) },
                        { Category: 'Liquidity', Metric: 'Quick Ratio', Value: ratios.liquidity.quickRatio.toFixed(2) },
                        { Category: 'Liquidity', Metric: 'Cash Ratio', Value: ratios.liquidity.cashRatio.toFixed(2) },
                        { Category: 'Leverage', Metric: 'Debt/Equity', Value: ratios.leverage.debtToEquity.toFixed(2) },
                        { Category: 'Leverage', Metric: 'Debt/Assets', Value: ratios.leverage.debtToAssets.toFixed(2) },
                        { Category: 'Leverage', Metric: 'Interest Coverage', Value: ratios.leverage.interestCoverage.toFixed(2) },
                        { Category: 'Efficiency', Metric: 'Asset Turnover', Value: ratios.efficiency.assetTurnover.toFixed(2) },
                        { Category: 'Efficiency', Metric: 'DSO (Days)', Value: Math.round(ratios.efficiency.dso) },
                        { Category: 'Efficiency', Metric: 'DPO (Days)', Value: Math.round(ratios.efficiency.dpo) }
                    ];

                case 'forecast':
                    if (window.budgetForecasting) {
                        const forecast = window.budgetForecasting.generateForecast(12);
                        return forecast.data.map(m => ({
                            Month: `${m.monthName} ${m.year}`,
                            Revenue: '$' + m.revenue.total.toLocaleString(),
                            Expenses: '$' + m.expenses.total.toLocaleString(),
                            'Net Income': '$' + m.netIncome.toLocaleString(),
                            'Net Margin': m.margins.net + '%'
                        }));
                    }
                    break;
            }
        }

        // Default sample data
        return [
            { Metric: 'Revenue', Value: '$2,450,000' },
            { Metric: 'Net Income', Value: '$384,000' },
            { Metric: 'Net Margin', Value: '15.7%' }
        ];
    }

    formatReportAsHTML(data, reportType) {
        let html = `<table><thead><tr>`;

        // Headers
        Object.keys(data[0]).forEach(key => {
            html += `<th>${key}</th>`;
        });
        html += `</tr></thead><tbody>`;

        // Rows
        data.forEach(row => {
            html += '<tr>';
            Object.values(row).forEach(value => {
                html += `<td>${value}</td>`;
            });
            html += '</tr>';
        });

        html += '</tbody></table>';
        return html;
    }

    // =====================================================
    // UTILITY METHODS
    // =====================================================

    downloadFile(content, filename, mimeType) {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    dateStamp() {
        return new Date().toISOString().split('T')[0];
    }

    trackExport(format, filename) {
        this.exportHistory.push({
            format,
            filename,
            timestamp: new Date().toISOString()
        });

        // Activity feed
        if (window.activityFeed) {
            window.activityFeed.add('report', `Exported ${format}`, filename);
        }

        // Toast notification
        if (window.toast) {
            window.toast.success('Export Complete', `${filename} downloaded successfully`);
        }
    }

    // =====================================================
    // EXPORT MODAL UI
    // =====================================================

    showExportModal() {
        const modal = document.createElement('div');
        modal.id = 'export-modal';
        modal.className = 'modal-enhanced';
        modal.innerHTML = `
            <div class="modal-backdrop" onclick="window.dataExport.closeModal()"></div>
            <div class="modal-content" style="max-width:500px;">
                <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:24px;">
                    <h2 style="color:#f39c12;margin:0;">📤 Export Data</h2>
                    <button onclick="window.dataExport.closeModal()" style="background:none;border:none;color:#fff;font-size:24px;cursor:pointer;">×</button>
                </div>

                <div style="margin-bottom:24px;">
                    <label style="color:#888;font-size:13px;display:block;margin-bottom:8px;">Report Type</label>
                    <select id="export-type" style="width:100%;padding:12px;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:8px;color:#fff;font-size:16px;">
                        <option value="summary">Financial Summary</option>
                        <option value="ratios">Financial Ratios</option>
                        <option value="forecast">12-Month Forecast</option>
                    </select>
                </div>

                <div style="margin-bottom:24px;">
                    <label style="color:#888;font-size:13px;display:block;margin-bottom:12px;">Export Format</label>
                    <div class="grid-responsive grid-2" style="gap:12px;">
                        <button class="glass-card" style="padding:20px;text-align:center;cursor:pointer;border:2px solid transparent;transition:all 0.2s;"
                                onclick="window.dataExport.exportAs('csv')"
                                onmouseover="this.style.borderColor='#f39c12'" onmouseout="this.style.borderColor='transparent'">
                            <div style="font-size:32px;margin-bottom:8px;">📄</div>
                            <div style="font-weight:600;">CSV</div>
                            <div style="color:#888;font-size:12px;">Spreadsheet compatible</div>
                        </button>
                        <button class="glass-card" style="padding:20px;text-align:center;cursor:pointer;border:2px solid transparent;transition:all 0.2s;"
                                onclick="window.dataExport.exportAs('excel')"
                                onmouseover="this.style.borderColor='#f39c12'" onmouseout="this.style.borderColor='transparent'">
                            <div style="font-size:32px;margin-bottom:8px;">📊</div>
                            <div style="font-weight:600;">Excel</div>
                            <div style="color:#888;font-size:12px;">XLSX format</div>
                        </button>
                        <button class="glass-card" style="padding:20px;text-align:center;cursor:pointer;border:2px solid transparent;transition:all 0.2s;"
                                onclick="window.dataExport.exportAs('pdf')"
                                onmouseover="this.style.borderColor='#f39c12'" onmouseout="this.style.borderColor='transparent'">
                            <div style="font-size:32px;margin-bottom:8px;">📑</div>
                            <div style="font-weight:600;">PDF</div>
                            <div style="color:#888;font-size:12px;">Print-ready document</div>
                        </button>
                        <button class="glass-card" style="padding:20px;text-align:center;cursor:pointer;border:2px solid transparent;transition:all 0.2s;"
                                onclick="window.dataExport.exportAs('json')"
                                onmouseover="this.style.borderColor='#f39c12'" onmouseout="this.style.borderColor='transparent'">
                            <div style="font-size:32px;margin-bottom:8px;">{ }</div>
                            <div style="font-weight:600;">JSON</div>
                            <div style="color:#888;font-size:12px;">Developer format</div>
                        </button>
                    </div>
                </div>

                ${this.exportHistory.length > 0 ? `
                    <div style="border-top:1px solid rgba(255,255,255,0.1);padding-top:16px;">
                        <div style="color:#888;font-size:13px;margin-bottom:8px;">Recent Exports</div>
                        ${this.exportHistory.slice(-3).reverse().map(exp => `
                            <div style="display:flex;justify-content:space-between;padding:8px 0;font-size:13px;">
                                <span>${exp.filename}</span>
                                <span style="color:#888;">${new Date(exp.timestamp).toLocaleString()}</span>
                            </div>
                        `).join('')}
                    </div>
                ` : ''}
            </div>
        `;

        document.body.appendChild(modal);
        setTimeout(() => modal.classList.add('active'), 10);
    }

    exportAs(format) {
        const reportType = document.getElementById('export-type')?.value || 'summary';
        const exporter = this.exportFinancialReport(reportType);

        switch (format) {
            case 'csv': exporter.toCSV(); break;
            case 'excel': exporter.toExcel(); break;
            case 'pdf': exporter.toPDF(); break;
            case 'json': exporter.toJSON(); break;
        }

        this.closeModal();
    }

    closeModal() {
        const modal = document.getElementById('export-modal');
        if (modal) {
            modal.classList.remove('active');
            setTimeout(() => modal.remove(), 300);
        }
    }
}

// Initialize globally
window.dataExport = new DataExport();

// Add to command palette
document.addEventListener('DOMContentLoaded', () => {
    if (window.commandPalette) {
        window.commandPalette.commands.push({
            icon: '📤',
            title: 'Export Data',
            desc: 'Export to CSV, Excel, PDF, or JSON',
            action: () => window.dataExport.showExportModal()
        });
    }
});
